name: trilium
base: core24
adopt-info: main
summary: Trilium Notes is a hierarchical note taking application
description: |
    Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases

    Source: https://github.com/TriliumNext/trilium
    Snap-Source: https://github.com/nbuechner/trilium-snap

grade: stable
confinement: strict


platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  trilium:
    command: usr/bin/trilium --no-sandbox
    plugs: [home, x11, desktop, removable-media, network, audio-playback, shared-memory, unity7 ]
    extensions: [ gnome ]
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libunit

plugs:
  shared-memory:
    private: true

parts:
  main:
    source: .
    plugin: dump
    override-build: |
      version=$(wget -qO- https://api.github.com/repos/TriliumNext/trilium/releases/latest | jq -r '.tag_name' | cut -c2-)
      URL=https://github.com/TriliumNext/trilium/releases/download/v${version}/TriliumNotes-v${version}-linux-x64.deb
      wget -q -O- $URL | dpkg -x - "$SNAPCRAFT_PART_INSTALL"
      rm -f $SNAPCRAFT_PART_INSTALL/usr/lib/trilium/chrome-sandbox
      rm -f $SNAPCRAFT_PART_INSTALL/etc/pulse/client.conf.d/01-enable-autospawn.conf
      craftctl set version="$version"
      craftctl default
    build-packages:
        - wget
        - jq
    stage-packages:
       - libgtk-3-0
       - libnotify4
       - libnss3
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libdrm2
       - libgbm1
       - libxcb-dri3-0
       - kde-cli-tools
       - trash-cli
       - libglib2.0-bin
       - pulseaudio
lint:
  ignore:
    - library

