name: trilium
base: core22
adopt-info: main
summary: Trilium Notes is a hierarchical note taking application
description: |
    Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases

    Source: https://github.com/zadam/trilium
    Snap-Source: https://github.com/nbuechner/trilium-snap

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  trilium:
    command: usr/bin/trilium --no-sandbox
    plugs: [home, x11, desktop, removable-media, network, audio-playback, shared-memory, unity7 ]
    extensions: [ gnome ]
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libunit

plugs:
  shared-memory:
    private: true

parts:
  main:
    source: .
    plugin: dump
    override-build: |
      version=$(wget -qO- https://api.github.com/repos/zadam/trilium/releases/latest | jq -r '.tag_name' | cut -c2-)
      URL=https://github.com/zadam/trilium/releases/download/v${version}/trilium_${version}_amd64.deb
      wget -q -O- $URL | dpkg -x - "$SNAPCRAFT_PART_INSTALL"
      craftctl set version="$version"
      craftctl default
    build-packages:
        - wget
        - jq
    stage-packages:
       - libgtk-3-0
       - libnotify4
       - libnss3
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libdrm2
       - libgbm1
       - libxcb-dri3-0
       - kde-cli-tools
       - trash-cli
       - libglib2.0-bin
       - pulseaudio
lint:
  ignore:
    - library

